[package]
name = "mathdoc"
version = "0.2.0"
entrypoint = "mathdoc.typ"
authors = ["Dorian Boully"]
description = "Documents mathématiques, énoncés et preuves."
compiler = "0.15.0"

[template]
path = "template"
entrypoint = "main.typ"
